#!/bin/bash

# Install Xmrig proxy
sudo apt-get update
sudo apt-get install -y git build-essential cmake libuv1-dev libssl-dev libhwloc-dev

git clone https://github.com/xmrig/xmrig-proxy.git
cd xmrig-proxy
mkdir build
cd build
cmake ..
make

# Set Xmrig proxy configuration
cat <<EOF > config.json
{
  "api": {
    "id": null,
    "worker-id": null
  },
  "http": {
    "enabled": true,
    "host": "0.0.0.0",
    "port": 5555,
    "access-token": null,
    "restricted": false
  },
  "log-file": null,
  "merge-multi-ssl": false,
  "merge-multi-algo": false,
  "merge-devfee": true,
  "tls": false,
  "daemon": {
    "enabled": false,
    "mode": "simple"
  },
  "pools": [
    {
      "algo": "rx/0",
      "coin": null,
      "url": "us.zephyr.herominers.com:1124",
      "user": "ZEPHYR3WLwbe4Nc9NgSMm1ZFcoZgLBLmqRnDqqRTYgjviBYvJ4GQjSQAwAGASA5CfwbS1AFXCGjmtXHTSBAER2fRjNbEnQGTBDD1X",
      "pass": "x",
      "rig-id": null,
      "pool-priority": 0
    }
  ]
}
EOF

# Run Xmrig proxy
./xmrig-proxy -c config.json
